In [5]:
import pandas as pd

In [10]:
df = pd.read_csv(r'C:\Users\U\Desktop\BolaPython\ML_data\OrderData.csv')
df.head()

,OrderID,BrandName,EmployeeCode,AgentName,MnagerName,Year,Month,OrderDate,OrderTime,DeliveryDate,...,SalesType,Statename,CityName,CustomerLatitude,CustomerLongitude,OriginalAddress,DistributorCode,DistributorName,SKUName,SKUcode
0,7651176,Blume Nigerian Limited PULL,BNLPL0032,EKWOMADU CHINYERE JOSEPHINE,SALAMI ROTIMI,2023,June,6/22/2023,4:05 PM,6/22/2023,...,SecondarySales,Lagos,Ojo,6.455355,3.243758,"Nk A1/045, Trade Fair, Ojo, Lagos, Nigeria",NEOBL8290665,Thiatro Int'L Ltd,Sonia- Tomato Mix -65gm x 50 Chicken Flavour (...,STC-6550SAC
1,7651176,Blume Nigerian Limited PULL,BNLPL0032,EKWOMADU CHINYERE JOSEPHINE,SALAMI ROTIMI,2023,June,6/22/2023,4:05 PM,6/22/2023,...,SecondarySales,Lagos,Ojo,6.455355,3.243758,"Nk A1/045, Trade Fair, Ojo, Lagos, Nigeria",NEOBL8290665,Thiatro Int'L Ltd,Sonia- Tomato Pepper & Onion - 65gm x 50 (Sachet),STP-6550SAC
2,7651176,Blume Nigerian Limited PULL,BNLPL0032,EKWOMADU CHINYERE JOSEPHINE,SALAMI ROTIMI,2023,June,6/22/2023,4:05 PM,6/22/2023,...,SecondarySales,Lagos,Ojo,6.455355,3.243758,"Nk A1/045, Trade Fair, Ojo, Lagos, Nigeria",NEOBL8290665,Thiatro Int'L Ltd,Sonia- Tomato Mix- 65gm x50( Sachet),STM-6550SAC
3,7651157,Blume Nigerian Limited PULL,BNLPL0032,EKWOMADU CHINYERE JOSEPHINE,SALAMI ROTIMI,2023,June,6/22/2023,4:04 PM,6/22/2023,...,SecondarySales,Lagos,Ojo,6.455355,3.243758,"Nk A1/045, Trade Fair, Ojo, Lagos, Nigeria",NEOBL8290665,Thiatro Int'L Ltd,Sonia- Tomato Pepper & Onion - 65gm x 50 (Sachet),STP-6550SAC
4,7651151,Blume Nigerian Limited PULL,BNLPL0032,EKWOMADU CHINYERE JOSEPHINE,SALAMI ROTIMI,2023,June,6/22/2023,4:04 PM,6/22/2023,...,SecondarySales,Lagos,Ojo,6.458896,3.252414,"Shop03poiy Star Plaza, Trade Fair, Ojo, Lagos,...",NEOBL8290665,Thiatro Int'L Ltd,Sonia- Tomato Mix- 65gm x50( Sachet),STM-6550SAC

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98387 entries, 0 to 98386
Data columns (total 36 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   OrderID            98387 non-null  int64
 1   BrandName          98387 non-null  object
 2   EmployeeCode       98387 non-null  object
 3   AgentName          98387 non-null  object
 4   MnagerName         98372 non-null  object
 5   Year               98387 non-null  int64
 6   Month              98387 non-null  object
 7   OrderDate          98387 non-null  object
 8   OrderTime          98387 non-null  object
 9   DeliveryDate       94727 non-null  object
 10  DeliveryTime       94727 non-null  object
 11  RecoDate           94730 non-null  object
 12  RecoTime           94730 non-null  object
 13  OrderSyncdate      97591 non-null  object
 14  OrderSyncTime      97591 non-null  object
 15  Quantity           98387 non-null  int64
 16  Sales              98387 non-null  int64
 17  Value              98387 non-null  int64
 18  OrderLatitude      98387 non-null  float64
 19  OrderLongitude     98387 non-null  float64
 20  OrderAddress       94564 non-null  object
 21  CustomerCode       98387 non-null  object
 22  CustomerName       98387 non-null  object
 23  ContactNumber      98387 non-null  int64
 24  CustomerStatus     98387 non-null  object
 25  CustomerType       98387 non-null  object
 26  SalesType          98387 non-null  object
 27  Statename          98097 non-null  object
 28  CityName           94760 non-null  object
 29  CustomerLatitude   98356 non-null  float64
 30  CustomerLongitude  98356 non-null  float64
 31  OriginalAddress    98225 non-null  object
 32  DistributorCode    95919 non-null  object
 33  DistributorName    95919 non-null  object
 34  SKUName            98387 non-null  object
 35  SKUcode            98387 non-null  object
dtypes: float64(4), int64(6), object(26)
memory usage: 27.0+ MB

In [13]:
df.isnull().sum()

OrderID                 0
BrandName               0
EmployeeCode            0
AgentName               0
MnagerName             15
Year                    0
Month                   0
OrderDate               0
OrderTime               0
DeliveryDate         3660
DeliveryTime         3660
RecoDate             3657
RecoTime             3657
OrderSyncdate         796
OrderSyncTime         796
Quantity                0
Sales                   0
Value                   0
OrderLatitude           0
OrderLongitude          0
OrderAddress         3823
CustomerCode            0
CustomerName            0
ContactNumber           0
CustomerStatus          0
CustomerType            0
SalesType               0
Statename             290
CityName             3627
CustomerLatitude       31
CustomerLongitude      31
OriginalAddress       162
DistributorCode      2468
DistributorName      2468
SKUName                 0
SKUcode                 0
dtype: int64

In [22]:
df.describe()

,OrderID,Year,Quantity,Sales,Value,OrderLatitude,OrderLongitude,ContactNumber,CustomerLatitude,CustomerLongitude
count,9.838700e+04,98387.000000,98387.00000,98387.000000,9.838700e+04,98387.000000,98387.000000,9.838700e+04,98356.000000,98356.000000
mean,6.233794e+06,2022.588218,5.38561,20058.894793,3.719108e+04,6.558814,3.363783,8.029752e+09,6.558649,3.364337
std,9.058115e+05,0.492159,28.77518,11497.545568,1.764077e+05,0.197283,0.343485,5.930447e+08,0.197338,0.344107
min,4.013809e+06,2022.000000,1.00000,100.000000,1.000000e+00,6.376665,2.875902,7.010188e+09,6.393382,2.875885
25%,5.491842e+06,2022.000000,1.00000,10159.000000,9.500000e+03,6.504076,3.269425,8.027729e+09,6.504533,3.269721
50%,6.333118e+06,2023.000000,2.00000,20068.000000,1.475000e+04,6.550813,3.352463,8.060844e+09,6.550711,3.352222
75%,7.045344e+06,2023.000000,5.00000,29998.500000,3.100000e+04,6.619403,3.390179,8.140389e+09,6.619653,3.390141
max,7.651176e+06,2023.000000,2200.00000,40000.000000,1.364000e+07,35.753888,51.334415,9.169726e+09,35.753888,51.334415

In [16]:
df.loc[df['Statename'].isnull(), 'Statename'] = 'Lagos'

In [23]:
df = df.dropna()

In [24]:
df.isnull().sum()

OrderID              0
BrandName            0
EmployeeCode         0
AgentName            0
MnagerName           0
Year                 0
Month                0
OrderDate            0
OrderTime            0
DeliveryDate         0
DeliveryTime         0
RecoDate             0
RecoTime             0
OrderSyncdate        0
OrderSyncTime        0
Quantity             0
Sales                0
Value                0
OrderLatitude        0
OrderLongitude       0
OrderAddress         0
CustomerCode         0
CustomerName         0
ContactNumber        0
CustomerStatus       0
CustomerType         0
SalesType            0
Statename            0
CityName             0
CustomerLatitude     0
CustomerLongitude    0
OriginalAddress      0
DistributorCode      0
DistributorName      0
SKUName              0
SKUcode              0
dtype: int64

In [25]:
df.sample(10)

,OrderID,BrandName,EmployeeCode,AgentName,MnagerName,Year,Month,OrderDate,OrderTime,DeliveryDate,...,SalesType,Statename,CityName,CustomerLatitude,CustomerLongitude,OriginalAddress,DistributorCode,DistributorName,SKUName,SKUcode
22365,7089528,Blume Nigerian Limited PULL,BNLPL0034,EZE CHIOMA MAUREEN,Emmanuel Tobore,2023,April,4/28/2023,4:02 PM,4/28/2023,...,SecondarySales,Lagos,Ikorodu,6.625367,3.507476,"Sabo Market, Ikorodu - Sabo, Ikorodu, Lagos, N...",NEOBL5670637,FRANCISCA STORES(SOPHISTIMARK),Sonia Tomato Mix - 2.2. Kg x 6 (TIN),STM-22006TIN
44015,6477494,Blume Nigerian Limited PULL,Bnlpl0028,OPARA NNEKA JENNIFER,SALAMI ROTIMI,2023,February,2/22/2023,12:41 PM,2/22/2023,...,SecondarySales,Lagos,Ojo,6.458370,3.251987,"Adamawa Plaza, Trade Fair, Ojo, Lagos, Nigeria",NEOBL5753822,Cycon & Company Ltd(Mr Chid),Sonia- Tomato Mix- 65gm x50( Sachet),STM-6550SAC
58755,5983565,Blume Nigerian Limited PULL,bnlpl0040,BABA TUNDE BLESSING,SALAMI ROTIMI,2022,December,12/24/2022,11:22 AM,12/24/2022,...,SecondarySales,Ogun,Ado Odo/Ota,6.505091,3.101311,"Market Road Odan Agbara, Ota, Ado Odo/ota, Og...",NEOBL5657570,BG GLOWS NIGERIA LTD,Sonia - Tomato Mix - SUP 400gm x 24 (Pack),STM-40024SUP
94420,4634197,Blume Nigerian Limited PULL,BNLPL0001,BABARINDE ABIGIAL,SAKA NURUDEEN,2022,August,8/9/2022,11:49 AM,8/9/2022,...,SecondarySales,Lagos,Epe,6.579488,3.976929,"Ikorodu Garage, Ayetoro, Epe, Lagos, Nigeria",NEOBL5328520,ELEHIBIRI CECELIA,Sonia- Tomato Mix- 65gm x50( Sachet),STM-6550SAC
6548,7455703,Blume Nigerian Limited PULL,BNLPL0043,ODEBIYI CHRISTIANA FUNMILAYO,OKUNADE ISMAIL ADEWUMI,2023,June,6/3/2023,5:10 PM,6/5/2023,...,SecondarySales,Lagos,Alimosho,6.599592,3.238530,"Outside Olane, Ayobo/ipaja, Alimosho, Lagos, N...",NEOBL8437350,Divine Topluck Resources Ltd,Sonia - Tomato Mix-400gm X24 ( Tin),STM-40024TIN
69976,5625919,Blume Nigerian Limited PULL,BNLPL0018,JAYEOBA TOSIN BOLAJI,Emmanuel Tobore,2022,November,11/15/2022,12:33 PM,11/15/2022,...,SecondarySales,Lagos,Ikorodu,6.620558,3.502452,"Benson, Ikorodu, Lagos, Nigeria",NEOBL5670637,FRANCISCA STORES(SOPHISTIMARK),Sonia - Tomato Mix-400gm X24 ( Tin),STM-40024TIN
44832,6457365,Blume Nigerian Limited PULL,BNLPL0032,EKWOMADU CHINYERE JOSEPHINE,SALAMI ROTIMI,2023,February,2/20/2023,1:18 PM,2/20/2023,...,SecondarySales,Lagos,Ojo,6.457945,3.250784,"Ea 005, Trade Fair, Ojo, Lagos, Nigeria",NEOBL8290665,Thiatro Int'L Ltd,Sonia - Tomato Mix - SUP 1.1kg x 12(Pack),STM-110012SUP
72776,5528962,Blume Nigerian Limited PULL,BNLPL0016,ADEBAYO ZAINAB,Emmanuel Tobore,2022,November,11/5/2022,9:33 AM,11/8/2022,...,SecondarySales,Lagos,Ikorodu,6.626522,3.508713,"C772 Sabo Market, Ikorodu - Sabo, Ikorodu, Lag...",NEOBL5696331,Redcliff Int'l Ltd - Ikorodu,Kivo - Good Time NDC 12 Gm x 200 (Sachets),KGT-12200SAC
60144,5948984,Blume Nigerian Limited PULL,BNLPL0009,MOSES OLAYEMI,ODUNTAN ROTIMI,2022,December,12/20/2022,1:24 PM,12/20/2022,...,SecondarySales,Lagos,Mushin,6.528643,3.353715,"No 7 Market, Mushin Market, Mushin, Lagos, Nig...",NEOBL3871244,FUMMY STORE NIG LTD.,Sonia - Tomato Mix-400gm X24 ( Tin),STM-40024TIN
72539,5539539,Blume Nigerian Limited PULL,bnlpl0040,BABA TUNDE BLESSING,SALAMI ROTIMI,2022,November,11/7/2022,9:34 AM,11/7/2022,...,SecondarySales,Ogun,Ado Odo/Ota,6.500509,3.100243,"Odo Era Beside Javy Filling Station Agbara, Ot...",NEOBL5657570,BG GLOWS NIGERIA LTD,Sonia - Tomato Mix - SUP 400gm x 24 (Pack),STM-40024SUP

In [27]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

# Load the data
df = pd.read_csv(r'C:/Users/U/Desktop/BolaPython/ML_data/OrderData.csv')

# Let's say 'date' and 'sales' are the columns
df['OrderDate'] = pd.to_datetime(df['OrderDate'])
df.set_index('OrderDate', inplace=True)

# Feature Engineering (adding a simple day feature for illustration)
df['OrderDate'] = df.index.day

# Splitting data
train = df[:-30]  # excluding last 30 days for testing
test = df[-30:]   # last 30 days for testing

X_train = train.drop('Sales', axis=1)
y_train = train['Sales']

X_test = test.drop('Sales', axis=1)
y_test = test['Sales']

# Training a simple linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Predictions
predictions = model.predict(X_test)

# Evaluation
mae = mean_absolute_error(y_test, predictions)
print(f'Mean Absolute Error: {mae}')

ValueError: could not convert string to float: 'Blume Nigerian Limited PULL'

In [28]:
print(X_train.shape)
print(y_train.shape)

(98357, 35)
(98357,)

In [29]:
print(X_train.dtypes)
print(y_train.dtypes)

OrderID                int64
BrandName             object
EmployeeCode          object
AgentName             object
MnagerName            object
Year                   int64
Month                 object
OrderTime             object
DeliveryDate          object
DeliveryTime          object
RecoDate              object
RecoTime              object
OrderSyncdate         object
OrderSyncTime         object
Quantity               int64
Value                  int64
OrderLatitude        float64
OrderLongitude       float64
OrderAddress          object
CustomerCode          object
CustomerName          object
ContactNumber          int64
CustomerStatus        object
CustomerType          object
SalesType             object
Statename             object
CityName              object
CustomerLatitude     float64
CustomerLongitude    float64
OriginalAddress       object
DistributorCode       object
DistributorName       object
SKUName               object
SKUcode               object
OrderDate              int64
dtype: object
int64

In [30]:
print(X_train.isnull().sum())
print(y_train.isnull().sum())

OrderID                 0
BrandName               0
EmployeeCode            0
AgentName               0
MnagerName             15
Year                    0
Month                   0
OrderTime               0
DeliveryDate         3643
DeliveryTime         3643
RecoDate             3640
RecoTime             3640
OrderSyncdate         795
OrderSyncTime         795
Quantity                0
Value                   0
OrderLatitude           0
OrderLongitude          0
OrderAddress         3820
CustomerCode            0
CustomerName            0
ContactNumber           0
CustomerStatus          0
CustomerType            0
SalesType               0
Statename             290
CityName             3624
CustomerLatitude       27
CustomerLongitude      27
OriginalAddress       162
DistributorCode      2462
DistributorName      2462
SKUName                 0
SKUcode                 0
OrderDate               0
dtype: int64
0