In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('PandasExample.csv',parse_dates=True)

In [4]:
df.head()

,FlightID,Date,RouteID,Departure Delay,AircraftID,Scheduled Departure,Avg Ticket Price,Total Fare,Flight Month,Flight Year
0,Flight1,41972,ORD-BOS,3.9,43,0.750000,450.0,74250.0,11,2014
1,Flight2,41967,ORD-JFK,6.8,61,0.791667,375.0,61875.0,11,2014
2,Flight3,42238,ORD-EWR,2.7,72,0.708333,247.5,44797.5,8,2015
3,Flight4,41833,ORD-LAX,3.8,172,0.729167,385.0,63525.0,7,2014
4,Flight5,42135,ORD-IAH,3.0,89,0.708333,200.0,36200.0,5,2015

In [5]:
df.set_index(['Flight Month','FlightID'])

                          Date  RouteID  Departure Delay  AircraftID  \
Flight Month FlightID
11           Flight1     41972  ORD-BOS              3.9          43
             Flight2     41967  ORD-JFK              6.8          61
8            Flight3     42238  ORD-EWR              2.7          72
7            Flight4     41833  ORD-LAX              3.8         172
5            Flight5     42135  ORD-IAH              3.0          89
...                        ...      ...              ...         ...
             Flight9632  42146  ORD-DEN              2.8          85
6            Flight9633  41818  ORD-DEN              1.6         185
12           Flight9634  42361  ORD-JFK              4.3         165
7            Flight9635  42188  ORD-MIA              2.8         201
5            Flight9636  42126  ORD-PHX              1.7         176

                         Scheduled Departure  Avg Ticket Price  Total Fare  \
Flight Month FlightID
11           Flight1                0.750000             450.0     74250.0
             Flight2                0.791667             375.0     61875.0
8            Flight3                0.708333             247.5     44797.5
7            Flight4                0.729167             385.0     63525.0
5            Flight5                0.708333             200.0     36200.0
...                                      ...               ...         ...
             Flight9632             0.312500             300.0     54300.0
6            Flight9633             0.291667             330.0     54450.0
12           Flight9634             0.708333             350.0     57750.0
7            Flight9635             0.833333             330.0     54450.0
5            Flight9636             0.520833             250.0     41250.0

                         Flight Year
Flight Month FlightID
11           Flight1            2014
             Flight2            2014
8            Flight3            2015
7            Flight4            2014
5            Flight5            2015
...                              ...
             Flight9632         2015
6            Flight9633         2014
12           Flight9634         2015
7            Flight9635         2015
5            Flight9636         2015

[9636 rows x 8 columns]

In [6]:
df.set_index(['Flight Month','FlightID'],inplace=True)

In [7]:
df.index

MultiIndex([(11,    'Flight1'),
            (11,    'Flight2'),
            ( 8,    'Flight3'),
            ( 7,    'Flight4'),
            ( 5,    'Flight5'),
            (12,    'Flight6'),
            ( 3,    'Flight7'),
            (11,    'Flight8'),
            ( 5,    'Flight9'),
            ( 9,   'Flight10'),
            ...
            ( 7, 'Flight9627'),
            ( 8, 'Flight9628'),
            ( 3, 'Flight9629'),
            ( 2, 'Flight9630'),
            (10, 'Flight9631'),
            ( 5, 'Flight9632'),
            ( 6, 'Flight9633'),
            (12, 'Flight9634'),
            ( 7, 'Flight9635'),
            ( 5, 'Flight9636')],
           names=['Flight Month', 'FlightID'], length=9636)

In [8]:
df.loc[6]

,Date,RouteID,Departure Delay,AircraftID,Scheduled Departure,Avg Ticket Price,Total Fare,Flight Year
FlightID,,,,,,,,
Flight29,41818,ORD-ATL,7.3,149,0.437500,220.0,40700.0,2014
Flight51,42164,ORD-JFK,1.5,3,0.791667,275.0,50875.0,2015
Flight74,41803,ORD-EWR,1.2,52,0.333333,247.5,40837.5,2014
Flight82,41802,ORD-SEA,3.3,70,0.750000,385.0,69685.0,2014
Flight88,41807,ORD-LAS,2.0,116,0.812500,302.5,55962.5,2014
...,...,...,...,...,...,...,...,...
Flight9597,42180,ORD-PHX,2.5,10,0.625000,275.0,50875.0,2015
Flight9604,42168,ORD-DFW,2.5,31,0.354167,220.0,40700.0,2015
Flight9622,42170,ORD-MIA,3.0,122,0.708333,330.0,61050.0,2015
Flight9626,41819,ORD-SFO,1.3,26,0.750000,412.5,76312.5,2014
Flight9633,41818,ORD-DEN,1.6,185,0.291667,330.0,54450.0,2014

In [9]:
df.iloc[6]

Date                     41726
RouteID                ORD-DEN
Departure Delay            1.7
AircraftID                 138
Scheduled Departure      0.625
Avg Ticket Price         300.0
Total Fare             55500.0
Flight Year               2014
Name: (3, Flight7), dtype: object